create table public.chat_messages (
  id bigint generated by default as identity primary key,
  room_code text not null references public.rooms(code) on delete cascade,
  author_player_id uuid references public.players(id) on delete set null,
  author_nickname text not null check (char_length(trim(author_nickname)) between 1 and 12),
  content text not null check (char_length(trim(content)) between 1 and 200),
  created_at timestamptz not null default now()
);

create index chat_messages_room_created_at_idx
  on public.chat_messages (room_code, created_at desc);

create index chat_messages_author_created_at_idx
  on public.chat_messages (author_player_id, created_at desc);

create trigger chat_messages_broadcast_change
after insert or delete on public.chat_messages
for each row execute function public.broadcast_room_change();

alter table public.chat_messages enable row level security;
revoke all on public.chat_messages from anon, authenticated;
